Indentation fix

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -1,69 +1,68 @@
 trigger:
-  - master
-  - features/*
-  - releases/*
+- master
+- features/*
+- releases/*
   
-  variables:
-    - group: npm-tokens
-    - name: nodeVersion
-      value: '16.13.0'
+variables:
+- group: npm-tokens
+- name: nodeVersion
+  value: '16.13.0'
   
-  jobs:
-  #################################################
-  - job: windows
-  #################################################
-    displayName: windows
-    pool:
-      vmImage: windows-2019
+jobs:
+#################################################
+- job: windows
+#################################################
+  displayName: windows
+  pool:
+    vmImage: windows-2019
+
+  steps:
+  - template: azure-pipelines-steps-node.yml
+    parameters:
+      nodeVersion: $(nodeVersion)
+
+  - template: azure-pipelines-steps-test-build.yml
   
-    steps:
-      - template: azure-pipelines-steps-node.yml
-        parameters:
-          nodeVersion: $(nodeVersion)
-  
-      - template: azure-pipelines-steps-test-build.yml
-  
-  #################################################
-  - job: linux
-  #################################################
-    displayName: Linux
-    pool:
-      vmImage: ubuntu-18.04
-  
-    steps:    
-      - template: azure-pipelines-steps-node.yml
-        parameters:
-          nodeVersion: $(nodeVersion)
-  
-      - template: azure-pipelines-steps-test-build.yml
-  
-      - task: PublishPipelineArtifact@1
-        inputs:
-          targetPath: 'node/_build'
-          artifactType: 'pipeline'
-          artifactName: 'npm-package'
-  
-      # For CI runs on master, automatically publish packages
-      - bash: |
-            echo //registry.npmjs.org/:_authToken=\${NPM_TOKEN} > .npmrc
-            npm publish || true # Ignore publish failures, usually will happen because package already exists
-        displayName: npm publish
-        workingDirectory: node/_build
-        condition: and(succeeded(), in(variables['build.reason'], 'IndividualCI', 'BatchedCI', 'Manual'), in(variables['build.sourcebranch'], 'refs/heads/master'))
-        env:
-          NPM_TOKEN: $(npm-automation.token)
-  
-  #################################################
-  - job: macOS
-  #################################################
-    displayName: macOS
-    pool:
-      vmImage: macOS-10.15
-  
-    steps:
-      - template: azure-pipelines-steps-node.yml
-        parameters:
-          nodeVersion: $(nodeVersion)
-  
-      - template: azure-pipelines-steps-test-build.yml
-  
+#################################################
+- job: linux
+#################################################
+  displayName: Linux
+  pool:
+    vmImage: ubuntu-18.04
+
+  steps:    
+  - template: azure-pipelines-steps-node.yml
+    parameters:
+      nodeVersion: $(nodeVersion)
+
+  - template: azure-pipelines-steps-test-build.yml
+
+  - task: PublishPipelineArtifact@1
+    inputs:
+      targetPath: 'node/_build'
+      artifactType: 'pipeline'
+      artifactName: 'npm-package'
+
+    # For CI runs on master, automatically publish packages
+  - bash: |
+        echo //registry.npmjs.org/:_authToken=\${NPM_TOKEN} > .npmrc
+        npm publish || true # Ignore publish failures, usually will happen because package already exists
+    displayName: npm publish
+    workingDirectory: node/_build
+    condition: and(succeeded(), in(variables['build.reason'], 'IndividualCI', 'BatchedCI', 'Manual'), in(variables['build.sourcebranch'], 'refs/heads/master'))
+    env:
+      NPM_TOKEN: $(npm-automation.token)
+
+#################################################
+- job: macOS
+#################################################
+  displayName: macOS
+  pool:
+    vmImage: macOS-10.15
+
+  steps:
+  - template: azure-pipelines-steps-node.yml
+    parameters:
+      nodeVersion: $(nodeVersion)
+
+  - template: azure-pipelines-steps-test-build.yml
